sudo: required
language: node_js
node_js:
  - "6.10"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm install
  - ng lint
  - ng test --single-run --progress false --reporters dots
  - ng build --prod --progress false

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && firebase deploy --token $FIREBASE_TOKEN
